### PR TITLE
revC1: add io port pinout to back silkscreen

### PR DESCRIPTION
**Pull request by electroniceel**
my suggestion for silkscreen as described in  #119

### CODE REVIEW

**Comment by whitequark** [comment]
Screenshot?

**Comment by marcan** [comment]
image

I think it's too busy (and non-symmetrical with the top); I would favor a sparser layout with a single character per pin. V for Vio, S for sense, 0-7 for the port pins, and the NC pins can just be left unmarked. The goal of putting the pinout on there isn't to tell people what the pins do (they should know that already), but just to remind existing users of which pin is which among the pins they already know are on there.

**Comment by electroniceel** [comment]
How about this:
silkscreen

**Comment by marcan** [comment]
Much better. Horizontal alignment seems a bit off, though. @whitequark, any opinions on Vio vs V for that pin? `+` could be another option.

**Comment by whitequark** [comment]
I'd say `V` fits nicely.

**Comment by electroniceel** [comment]
Updated version using "V" instead of "Vio". I also aligned all the numbers and letters to the respective holes of the connectors.

silkscreen

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
