### PR TITLE
Temporarily work around issue #382

### PR DESCRIPTION
**Pull request by whitequark**
Display a better message so that people don't think the units we already have with firmware we cannot change (I think @esden is not able to reflash them anymore) are faulty in any way.

### CODE REVIEW

**Comment by esden** [comment]
I have not packed them into boxes yet. I can still reflash all the early birds.

**Comment by whitequark** [comment]
Got it. Let's see if @VioletEternity is able to narrow down the cause of this problem.

**Comment by VioletEternity** [comment]
When the device is in a failed state, running a command now results in:

```
>glasgow voltage
E: glasgow.cli: failed to enumerate a device; try unplugging it and plugging it back in

>
```

After following the instructions the command does succeed. (Although I had to reset it twice just now.)

**Comment by whitequark** [comment]
Closed in favor of https://github.com/GlasgowEmbedded/glasgow/pull/395.

**Pull request closed without merging**
