### PR TITLE
revC3 hardware

### PR DESCRIPTION
**Pull request by esden**
This is the newest version of the Glasgow hardware. This is what we are shipping as part of the [CrowdSupply](https://www.crowdsupply.com/1bitsquared/glasgow) campaign.

I think we are now ready to merge it to main.

Closes: #255

### CODE REVIEW

**Comment by whitequark** [comment]
Can you export the design files for revC3 under a subdirectory, like it's done for all earlier revisions?

**Comment by whitequark** [comment]
Also, I see you converted the symbol library to V6 format, but that left the old one in tree. Can you delete it please?

**Comment by esden** [comment]
I ran out of cycles for today. If @electroniceel or someone else has a moment please feel free to address these issues. It will be a few days before I will be able to get back to this, but I will if no-one beats me to it. :)

**Comment by whitequark** [comment]
That's okay! I might do it myself. That said I'd be happy if someone else did it.

**Comment by whitequark** [comment]
Can you delete the empty `glasgow.sch` as well?

**Review by whitequark — APPROVED** [review]
This is now all complete, except for BOM. I'll open another issue for BOM because I'd really like to just get this over with already.

**Pull request merged**
