### PR TITLE
Component clarification

### PR DESCRIPTION
**Pull request by Wmyers559**
This is an attempt to update some of the component references to contain the proper part numbers/datasheet links/values/etc. Any suggestions are _very_ welcome.

### CODE REVIEW

**Comment by whitequark** [comment]
Looks perfect! If you're in a mood to do more updates, it would be really great if you could go through Mouser part numbers for other resistors and check that they're correct, I'm pretty sure many of them are out of sync. If not, that's also fine and I'll just merge this.

**Comment by Wmyers559** [comment]
Will do! I also plan to update the other LED part numbers (pink & white, though if you want a different blue, I just picked one from the same series as the existing LEDs).

For the ferrite bead specified, is there a specified impedance, etc?

I'll try to get these updates done in the next day or so.

**Comment by whitequark** [comment]
The pink and blue LEDs are specific LEDs @esden pointed out... I hope he still has the references. Mouser has the white ones but the pink and blue ones need to be matched and Mouser doesn't have any pink ones. Which is a glaring omission :S

**Comment by Wmyers559** [comment]
From the IRC logs, the pink LEDs are OptoSupply OSK40603C1E (https://lcsc.com/product-detail/Light-Emitting-Diodes-LED_OptoSupply-OSK40603C1E_C268294.html), although I don't know if that matches what @esden is using. I haven't found anything for the blue LEDs yet. For the white LEDs, do you have a specific part/requirements? I believe the current schematic part number is for a green LED.

**Comment by whitequark** [comment]
> I haven't found anything for the blue LEDs yet.

There should be a matching OptoSupply blue LED from the same series, I think.

> For the white LEDs, do you have a specific part/requirements?

Yes. @marcan has calibrated the resistors for the specific combination of LEDs he has on his revC0. He has the necessary MPNs for all of D6-D10. I think we can leave that part to him.

**Comment by Wmyers559** [comment]
Sounds good to me! I'll go through and check the resistor and capacitor values. Do you have a preference for the values of the u1 capacitors? One currently linked datasheet has 150nF, @esden's BOM keys suggest 100nF, and the other datasheet is for 4.7uF.

**Comment by marcan** [comment]
u1 (0.1μ) is supposed to be 100nF; any mixed values are a result of bad copypasta.

I just asked @GregDavill about the LEDs, since he has the MPNs for those that he used for my unit (except the pinks, which I got from LCSC).

**Comment by whitequark** [comment]
> I just asked @gregdavill about the LEDs, since he has the MPNs for those that he used for my unit (except the pinks, which I got from LCSC).

Oh, so we're using blues from Mouser? I see. Can you post a photo of the matched LEDs by the way? I'm not sure if I've missed it or just forgotten...

**Comment by marcan** [comment]
I think that was DigiKey. Photos are in [this](https://twitter.com/marcan42/status/1103642165475864577?s=19) Twitter thread.

**Comment by whitequark** [comment]
Ah, I even retweeted those.

**Comment by marcan** [comment]
@gregdavill says:

Green: Wurth Electronics 150060GS75000
Yellow: 150060YS75000
Red: 150060RS75000
Blue: 150060BS75000
White: SMLEN3WBC8W1

**Comment by Wmyers559** [comment]
The only components that are missing part numbers now are:
 - The ferrite bead
 - Optional connectors like the LVDS header, AUX header, etc

**Comment by Wmyers559** [comment]
I'm pretty sure that this can be merged now, pending any pressing issues that you see.

**Comment by whitequark** [comment]
Thank you for this work! The only issue is that the PR has a few commits of the general form "fix a part of the other commit" or "misc fixes", which makes the history a bit more complicated than necessary. Normally (when dealing with code) I would ask you to rebase, but with KiCAD files it's not really possible, so can you please squash the commits and put a summary of all the changes into the description?

**Comment by Wmyers559** [comment]
Will do!

**Comment by whitequark** [comment]
Thank you again.

**Comment by Wmyers559** [comment]
Not a problem! Glad I could help.

**Pull request merged**
