### PR TITLE
Add protection resistor between fpga and the level shifter for the sync connector

### PR DESCRIPTION
**Pull request by electroniceel**
My implementation for #125.

I had to move U32 and some tracks a bit to make room for the resistor. But I think there is enough clearance everywhere now.
top
3d

### CODE REVIEW

**Comment by marcan** [comment]
I know why you moved the via next to U24, and I don't blame you for it, but I'm going to try to find a way of doing this without that :-)

**Comment by marcan** [comment]
My take:

image

image

This has the nice property that it also orients the shifter the same as the others.

**Comment by electroniceel** [comment]
what is the problem with moving the via?
I think there is enough clearance between the via and the pad so that no solder is sucked into the via. Or is it the beauty of the vias being in a line & symmetrical?

I think the downside of your solution is the 3v3-via between the pads of U32: it seems to touch the pads, so solder could be sucked down.

**Comment by marcan** [comment]
The vias ought to be tented, so that shouldn't be an issue. We already have a few other vias closer to the pads than that without trouble.

It's a beauty thing; all the shifters have an identical layout. If I really wanted to move that via closer I'd end up moving them all to match.

**Comment by electroniceel** [comment]
Ok, yours is more beautiful.

But you could still move the 3v3-via a bit up & right without problems. So even if the tenting isn't complete it doesn't create a problem. Via tenting tends to be not that reliable in my experience. You need plugged vias for that, but that is $$$

**Pull request closed without merging**
