### PR TITLE
Add kitspace.yml for rev C1

### PR DESCRIPTION
**Pull request by John-K**
Add kitspace yaml to facilitate ordering rev C1 boards and components via https://kitspace.org

### CODE REVIEW

**Comment by whitequark** [comment]
What happens when we add another board release? The format of the Kitpace file doesn't seem to allow for more than one per repository at a time.

**Comment by John-K** [comment]
> What happens when we add another board release? The format of the Kitpace file doesn't seem to allow for more than one per repository at a time.

I believe this is implemented by using `multi:` as per https://github.com/kitspace/kitspace#the-multi-field

**Comment by whitequark** [comment]
Okay, can you use that right away?

**Comment by John-K** [comment]
Good question, I'm asking the Kitspace maintainers now

**Comment by John-K** [comment]
Closing in favor of #195

**Pull request closed without merging**
