### PR TITLE
SRST# support in jtag-openocd

### PR DESCRIPTION
**Pull request by neuschaefer**
Sometimes it's useful to trigger a DUT reset from within JTAG-adjacent logic. For example OpenOCD uses this feature as part of its remote-bitbang protocol, and the [ARM 20-pin JTAG connector](https://developer.arm.com/documentation/dui0499/k/arm-dstream-target-interface-connections/the-arm-jtag-20-connector-pinouts-and-interface-signals/arm-jtag-20-pinouts?lang=en) includes an SRST# pin. This PR adds SRST# support to the jtag-probe and jtag-openocd applets.

### Alternatives

- The SRST pin could be added to jtag-openocd only, as it's not strictly part of a JTAG interface.
- SRST could be renamed RESET, but I think that would be more ambiguous.

### CODE REVIEW

**Comment by whitequark** [comment]
It's unclear to me whether SRST# should be a part of the generic JTAG probe applet. It is not a part of IEEE 1149.1.

**Comment by neuschaefer** [comment]
I'm unsure myself, I'm fine with either way (having SRST in jtag-probe or only in jtag-openocd)

**Comment by neuschaefer** [comment]
I'll probably change it to jtag-openocd only, because it is more easily correct that way.

**Comment by whitequark** [comment]
Happy to merge that right away.

**Review by whitequark — APPROVED** [review]
Thank you!

**Pull request merged**
