### PR TITLE
Finalised revC3 hardware description documentation.

### PR DESCRIPTION
**Pull request by gsuberland**
git was being a huge pain while trying to do a rebase/squash for finalising #544, and I didn't have the spoons to fight with it, so I just moved the final document over to a new branch.

### CODE REVIEW

**Review by whitequark — APPROVED** [review]
Thanks! I'm not going to go through all the changes; I assume they're good enough, and worst case we can update it later.

**Comment by whitequark** [comment]
Something I've realized is still missing is a link from the ToC; right now the `revisions/revC3` page is an orphan. So I actually can't merge this as-is...

**Comment by gsuberland** [comment]
Thanks for sorting this! I was really not in the right headspace to be fighting with git last night.

**Comment by whitequark** [comment]
No worries!

**Pull request merged**
