### PR TITLE
XC95000XL: Merging the tool into the applet to migrate from .bit to .jed

### PR DESCRIPTION
**Pull request by brainstorm**

### CODE REVIEW

**Comment by brainstorm** [comment]
I'll be revisiting this soon as I've successfully dumped the target CPLD from my original DNA sequencer repair project :)

I'm posting this comment as self-documentation/thoughts as go through Glasgow's code to easily context-switch when I retake this task.

Given that I have the contents of isdata.data, i.e:

<glasgow.arch.xilinx.xc9500xl.DR_ISDATA valid=1 strobe=0 data=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000>
<glasgow.arch.xilinx.xc9500xl.DR_ISDATA valid=1 strobe=0 data=00000010000100000000000100000000000000000000000100000000000010100000000000000000000000000000000000000000000000000000000000000000>

I was looking for a JED struct to fill to serialize those fuse states... I found the [jesd3 parser within Glasgow protocols](https://github.com/GlasgowEmbedded/glasgow/blob/main/software/glasgow/protocol/jesd3.py), but I didn't find a JED **writer** (serializer), so I guess I'll have to write a struct that conforms with [the official JEDEC spec](ttps://ia800102.us.archive.org/23/items/JEDECJESD3C/JEDEC_JESD3-C.pdf) (shall I include this one in the glasgow-archive repo if it's not already?).

The example data shown above are fuses representation, I'm obtaining that [via a print() inside _fvfyi function](https://github.com/GlasgowEmbedded/glasgow/blob/3cabc7c918da22090290dcc27279a263454fbe7a/software/glasgow/applet/program/xc9500xl/__init__.py#L354-L372).

**Comment by whitequark** [comment]
> I guess I'll have to write a struct that conforms with the official JEDEC spec (shall I include this one in the glasgow-archive repo if it's not already?)

All you really need for serializing a JED is a bitarray of fuses. Once you can convert the data that has been read out to that, I'll assist you with a JED writer.

**Comment by brainstorm** [comment]
Thanks Catherine! When I was exploring this, I was wondering to which extent the [JED writer had to conform with the original spec](https://ia800102.us.archive.org/23/items/JEDECJESD3C/JEDEC_JESD3-C.pdf) in all its facets or just-functional, i.e:

Screen Shot 2021-12-16 at 9 01 24 pm

**Comment by whitequark** [comment]
All you _need_ to do is to write `QF<nfuses>*` `F0*`, and `L<nfuse> <data>`.

**Comment by whitequark** [comment]
Obsoleted by #477.

**Pull request closed without merging**
