### PR TITLE
manual: use/repl-script: add details about the REPL and Script interfaces, along with examples

### PR DESCRIPTION
**Pull request by attie**
Finally, some words around using the REPL and script interfaces... I've included I2C, UART and WS2812 demos... I'll happily have a rummage for an SPI device to add that if it's deemed important.

### CODE REVIEW

**Comment by whitequark** [comment]
Style nit: do you think you can use em-dashes? This is currently inconsistent across the manual and it's bugging me. (We could use that being a part of our documentation style guide.)

Other than that the main high-level feedback I have is that I'm not sure if tabs are the right thing here.

**Comment by attie** [comment]
> do you think you can use em-dashes?

Sure.

> We could use that being a part of our documentation style guide

I'll add it, along with a handy "copy me" example. 🙃

> I'm not sure if tabs are the right thing here.

I'll change for sub-headings... my only thought was that it becomes quite a long page.
I think due to this I'm less inclined to add many more examples if they're not tabs... thoughts?

**Comment by whitequark** [comment]
> I'll change for sub-headings... my only thought was that it becomes quite a long page.

I do see that but tabs are an accessibility concern here. The idea with tabs is that you do not need the other items, *period* (like if they're on an OS that does not concern you); not that you do not need other items at the same time.

**Comment by whitequark** [comment]
> I'll add it, along with a handy "copy me" example. 🙃
> 
> >

You can just use `---` I think--you don't actually need to use the — symbol.

**Comment by attie** [comment]
> I do see that but tabs are an accessibility concern here.

Yeah, I was back and forth with that being one of the arguments.

**Review by whitequark — APPROVED** [review]
Style guide looks good. For the rest I will go with a "post-merge review": I merge this now and then later, when I have more uninterrupted time, we can look closer again (possibly together!) and work out if more improvement can be made.

**Pull request merged**
