### PR TITLE
docs: minor fixes.

### PR DESCRIPTION
**Pull request by charlottia**
Spotted scanning the docs while exercising my device :3

### CODE REVIEW

**Comment by charlottia** [comment]
CI failure fetching The 36 Lessons of Vivec >_>

**Comment by whitequark** [comment]
> CI failure fetching The 36 Lessons of Vivec >_>

Yeah, we should add that to the exclusion list...

**Review by whitequark — APPROVED** [review]
Thanks!

**Comment by whitequark** [comment]
Oh right, status checks don't pass. Would you mind adding an exclusion for the Morrowind wiki? It's a regex in `docs/manual/conf.py`.

**Comment by kivikakk** [comment]
Ah, of course! Done, thank you; will need auto-merge re-enabled now.

**Comment by charlottia** [comment]
Ah, of course! Done, thank you; will need auto-merge re-enabled now.

(is2g firefox containers you are not good enough for me)

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
