### PR TITLE
applet.selftest: fixes for revC0 and later

### PR DESCRIPTION
**Pull request by TomKeddie**
https://github.com/GlasgowEmbedded/glasgow/issues/151

### CODE REVIEW

**Comment by whitequark** [comment]
That doesn't actually fix the false positives.

**Comment by TomKeddie** [comment]
Agreed, I'll read the pr more closely.

**Comment by TomKeddie** [comment]
@whitequark I'm not sure exactly what more we can do here without more control over the ice40 pullups (do we have this now?).

pins-pull already does a walking ones test of the pullups.

```I: g.device.hardware: device already has bitstream ID a1b696ec5f45600cb03d5603c6fa9202
I: g.cli: running handler for applet 'selftest'
I: g.applet.internal.selftest: running self-test mode pins-pull
D: g.applet.internal.selftest: pins-pull: oe=0000000000000000 o=0000000000000000 oe_pull=0000000000000000 o_pull=0000000000000000 i=0000000000000000
D: g.applet.internal.selftest: pins-pull: oe=1111111111111111 o=1111111111111111 oe_pull=1111111111111111 o_pull=1111111111111111 i=1111111111111111
D: g.applet.internal.selftest: pins-pull: oe=0000000000000001 o=0000000000000001 oe_pull=0000000000000001 o_pull=1111111111111111 i=0000000000000001
D: g.applet.internal.selftest: pins-pull: oe=0000000000000010 o=0000000000000010 oe_pull=0000000000000010 o_pull=1111111111111111 i=0000000000000010
D: g.applet.internal.selftest: pins-pull: oe=0000000000000100 o=0000000000000100 oe_pull=0000000000000100 o_pull=1111111111111111 i=0000000000000100
D: g.applet.internal.selftest: pins-pull: oe=0000000000001000 o=0000000000001000 oe_pull=0000000000001000 o_pull=1111111111111111 i=0000000000001000
D: g.applet.internal.selftest: pins-pull: oe=0000000000010000 o=0000000000010000 oe_pull=0000000000010000 o_pull=1111111111111111 i=0000000000010000
D: g.applet.internal.selftest: pins-pull: oe=0000000000100000 o=0000000000100000 oe_pull=0000000000100000 o_pull=1111111111111111 i=0000000000100000
D: g.applet.internal.selftest: pins-pull: oe=0000000001000000 o=0000000001000000 oe_pull=0000000001000000 o_pull=1111111111111111 i=0000000001000000
D: g.applet.internal.selftest: pins-pull: oe=0000000010000000 o=0000000010000000 oe_pull=0000000010000000 o_pull=1111111111111111 i=0000000010000000
D: g.applet.internal.selftest: pins-pull: oe=0000000100000000 o=0000000100000000 oe_pull=0000000100000000 o_pull=1111111111111111 i=0000000100000000
D: g.applet.internal.selftest: pins-pull: oe=0000001000000000 o=0000001000000000 oe_pull=0000001000000000 o_pull=1111111111111111 i=0000001000000000
D: g.applet.internal.selftest: pins-pull: oe=0000010000000000 o=0000010000000000 oe_pull=0000010000000000 o_pull=1111111111111111 i=0000010000000000
D: g.applet.internal.selftest: pins-pull: oe=0000100000000000 o=0000100000000000 oe_pull=0000100000000000 o_pull=1111111111111111 i=0000100000000000
D: g.applet.internal.selftest: pins-pull: oe=0001000000000000 o=0001000000000000 oe_pull=0001000000000000 o_pull=1111111111111111 i=0001000000000000
D: g.applet.internal.selftest: pins-pull: oe=0010000000000000 o=0010000000000000 oe_pull=0010000000000000 o_pull=1111111111111111 i=0010000000000000
D: g.applet.internal.selftest: pins-pull: oe=0100000000000000 o=0100000000000000 oe_pull=0100000000000000 o_pull=1111111111111111 i=0100000000000000
D: g.applet.internal.selftest: pins-pull: oe=1000000000000000 o=1000000000000000 oe_pull=1000000000000000 o_pull=1111111111111111 i=1000000000000000
I```

**Comment by whitequark** [comment]
Measure capacitance by observing decay time. You are not required to implement this.

**Comment by TomKeddie** [comment]
Ok, thanks - I'll just close this.

**Pull request closed without merging**
