### PR TITLE
manual: develop/firmware: write the page

### PR DESCRIPTION
**Pull request by whitequark**
[Rendered](https://whitequark.github.io/glasgow/manual-develop/firmware/develop/firmware.html)

### CODE REVIEW

**Review by attie — APPROVED** [review]
Looks good to me!

Only one very minor thought about the clarity of the "commit everything, then build, then commit ihex" process... but I think it's clear enough and protected by CI, so no need to change it.

**Comment by whitequark** [comment]
> Only one very minor thought about the clarity of the "commit everything, then build, then commit ihex" process...

It doesn't really *have* to be this way but it avoids extraneous diffs of the ihex file in the repository which keeps it a little bit smaller, and also makes bisecting easier. It's a soft requirement.

**Comment by attie** [comment]
> It's a soft requirement.

Oh, I thought it was a hard requirement because the binary includes the commit hash(?) ... can't be self referential, etc...

Fine either way.

**Comment by whitequark** [comment]
> Oh, I thought it was a hard requirement because the binary includes the commit hash(?) ... can't be self referential, etc...

What I mean is that the file being updated *exclusively in the last commit* is a soft requirement. Unless you update it separately *at least* in the last commit nothing would work, but besides that the CI doesn't really care.

**Pull request merged**
