### PR TITLE
test: use required_revision for assertBulids

### PR DESCRIPTION
**Pull request by anuejn**
this is cherry picked from #486

### CODE REVIEW

**Review by whitequark — APPROVED** [review]

**Comment by whitequark** [comment]
@anuejn The code is wrong.

**Comment by anuejn** [comment]
sorry, should be fixed now

**Comment by whitequark** [comment]
@anuejn Nope, still wrong.

**Comment by anuejn** [comment]
sorry \*self facepalm\*

**Review by whitequark — APPROVED** [review]
Thanks!

**Pull request merged**
