### PR TITLE
U13 function description updated. U13 has same function as U20 (was same as U21).

### PR DESCRIPTION
**Pull request by id43**
manual: revisions/revC3: U13 function description was the same as U12 and U21. Should be the same as U20. Probably copy/paste error.

### CODE REVIEW

**Comment by whitequark** [comment]
Could you change the git commit message to start with `manual: revisions/revC3: ...` according to our [guidelines](https://glasgow-embedded.org/latest/contribute.html#writing-commit-messages) please?

**Comment by whitequark** [comment]
Oh, that just edited the PR description, the git commit message is exactly the same.

**Comment by id43** [comment]
Never too old to learn some new tricks. I hope this amendment is OK.

**Comment by whitequark** [comment]
Thanks so much!

**Pull request merged**
