### PR TITLE
applet.interface.uart: allow to invert the UART line signals (=idle low)

### PR DESCRIPTION
**Pull request by electroniceel**
Adds the --invert {RX,TX,RXTX,both,none} cli argument and the corresponding
build-time parameters to the uart gateware.

This option comes in handy when driving UART through inverting optocouplers for example.

@whitequark sorry, I haven't done a conversion to nMigen of the module. I don't have confidence in my (n)Migen skills enough for this.

### CODE REVIEW

**Comment by whitequark** [comment]
I'd probably use two arguments, `--invert-rx` and `--invert-tx`, instead of one with five possible values.

**Comment by electroniceel** [comment]
> I'd probably use two arguments, `--invert-rx` and `--invert-tx`, instead of one with five possible values.

That was the other option I was considering. I can change it.

Did you look at the other code?

**Comment by whitequark** [comment]
The code is basically fine I think.

**Comment by electroniceel** [comment]
Ok, new arguments implemented.

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
